export const GET_ONE_CLIENT_LOADING = 'GET_ONE_CLIENT_LOADING';
export const GET_ONE_CLIENT_SUCCESS = 'GET_ONE_CLIENT_SUCCESS';
export const GET_ONE_CLIENT_FAIL = 'GET_ONE_CLIENT_FAIL';

export const DELETE_ONE_CLIENT_LOADING = 'DELETE_ONE_CLIENT_LOADING';
export const DELETE_ONE_CLIENT_SUCCESS = 'DELETE_ONE_CLIENT_SUCCESS';
export const DELETE_ONE_CLIENT_FAIL = 'DELETE_ONE_CLIENT_FAIL';
