export const GET_ONE_CLIENT_LOADING = 'GET_ONE_CLIENT_LOADING';
export const GET_ONE_CLIENT_SUCCESS = 'GET_ONE_CLIENT_SUCCESS';
export const GET_ONE_CLIENT_FAIL = 'GET_ONE_CLIENT_FAIL';

export const DELETE_ONE_CLIENT_LOADING = 'DELETE_ONE_CLIENT_LOADING';
export const DELETE_ONE_CLIENT_SUCCESS = 'DELETE_ONE_CLIENT_SUCCESS';
export const DELETE_ONE_CLIENT_FAIL = 'DELETE_ONE_CLIENT_FAIL';

export const WARN_ONE_CLIENT_LOADING = 'WARN_ONE_CLIENT_LOADING';
export const WARN_ONE_CLIENT_SUCCESS = 'WARN_ONE_CLIENT_SUCCESS';
export const WARN_ONE_CLIENT_FAIL = 'WARN_ONE_CLIENT_FAIL';

export const REMOVEWARN_ONE_CLIENT_LOADING = 'REMOVEWARN_ONE_CLIENT_LOADING';
export const REMOVEWARN_ONE_CLIENT_SUCCESS = 'REMOVEWARN_ONE_CLIENT_SUCCESS';
export const REMOVEWARN_ONE_CLIENT_FAIL = 'REMOVEWARN_ONE_CLIENT_FAIL';

export const SEND_MAIL_LOADING = 'SEND_MAIL_LOADING';
export const SEND_MAIL_SUCCESS = 'SEND_MAIL_SUCCESS';
export const SEND_MAIL_FAIL = 'SEND_MAIL_FAIL';
