export const UPDATE_AMOUNT_LOADING = 'UPDATE_AMOUNT_LOADING';
export const UPDATE_AMOUNT_SUCCESS = 'UPDATE_AMOUNT_SUCCESS';
export const UPDATE_AMOUNT_FAIL = 'UPDATE_AMOUNT_FAIL';


export const UPDATE_PROFIT_LOADING = 'UPDATE_PROFIT_LOADING';
export const UPDATE_PROFIT_SUCCESS = 'UPDATE_PROFIT_SUCCESS';
export const UPDATE__PROFIT_FAIL = 'UPDATE_PROFIT_FAIL';
